/* ══════════════════════════════════════════════════════════════════════════
   Reportes — las tablas en Supabase

   Se corre desde el panel de Supabase:
     SQL Editor → New query → borrar lo que haya → pegar todo esto → Run

   Se puede correr las veces que haga falta: todo está escrito para no romper
   nada si las tablas ya existen. No borra datos.

   ⚠️ LEER ESTO, QUE NO ES UN DETALLE

   Esta base va SIN login, por decisión tomada a propósito. Eso quiere decir que
   las tablas de acá quedan abiertas a quien tenga la clave pública de la app, y
   esa clave está dentro de `js/nube.js`, en un repositorio público. Cualquiera
   que la encuentre puede leer, cambiar y borrar todo lo que haya acá.

   Se aceptó ese riesgo porque:
     · los datos son avance de obra, no datos personales ni contraseñas;
     · cada aparato conserva su copia completa en IndexedDB, así que vaciar la
       nube no borra el trabajo de nadie;
     · los .xlsx semanales siguen siendo el respaldo de verdad.

   Si algún día se quiere cerrar: se agrega una columna `user_id uuid default
   auth.uid()` a todas las tablas, se cambian las reglas de `to anon` a
   `to authenticated` con `user_id = auth.uid()`, y se le vuelve a poner el
   formulario de entrar a la app.
   ══════════════════════════════════════════════════════════════════════════ */

/* ── Reportes importados ───────────────────────────────────────────────────
   La llave es un uid que genera el aparato al importar el Excel, y no un
   número que ponga la base. Así el mismo reporte tiene la misma identidad en
   la compu, en el celular y en la nube, y sincronizar se vuelve repetible:
   subir dos veces el mismo reporte no lo duplica. */
create table if not exists public.reportes (
  uid         uuid primary key,
  nombre      text not null,
  fecha       timestamptz not null,
  hoja        text,
  total_filas integer,
  mapeo       jsonb,
  creado      timestamptz not null default now()
);

/* ── Las casas de cada reporte ────────────────────────────────────────────
   Al borrar un reporte se van sus filas solas (on delete cascade). */
create table if not exists public.filas (
  id              bigint generated by default as identity primary key,
  reporte_uid     uuid not null references public.reportes (uid) on delete cascade,
  casa            text not null,
  casa_norm       text not null,
  porcentaje      integer,
  etapa           integer,
  complementarias integer,
  datos           jsonb
);

create index if not exists filas_por_reporte on public.filas (reporte_uid);
create index if not exists filas_por_casa    on public.filas (casa_norm);

/* ══ Lo que va por casa y no por reporte ══════════════════════════════════
   Las tres tablas que siguen tienen la misma forma: una fila por número de
   casa, con casa_norm de llave. Eso es a propósito.

   Son lo único que NO se puede regenerar del Excel, y al ir por casa y no por
   reporte, sobreviven cuando entra el reporte de la semana siguiente, que es
   justo cuando sirven.
   ═══════════════════════════════════════════════════════════════════════ */

/* ── Las marcas de «añadido» ──────────────────────────────────────────────
   Se vencen a los 7 días; de eso se encarga la app. Con casa_norm de llave,
   volver a subir la misma marca la actualiza en vez de duplicarla. */
create table if not exists public.marcas (
  casa_norm text primary key,
  fecha     timestamptz not null
);

/* ── El código de cada casa ───────────────────────────────────────────────
   Lo escribe la persona a mano y no se vence nunca. La fecha no es adorno:
   es lo que decide cuál gana si la compu y el celular tienen códigos
   distintos para la misma casa. */
create table if not exists public.codigos (
  casa_norm text primary key,
  codigo    text not null,
  fecha     timestamptz not null
);

/* ── Las casas terminadas ─────────────────────────────────────────────────
   El check de «bitácora cerrada» de cada casa. Lo pone y lo quita la persona
   a mano; llegar al 100 % en el Excel no lo pone solo.

   Hay una fila por cada casa que se haya tocado alguna vez, esté el check
   puesto o no: «cerrada» dice cómo quedó y «fecha» cuándo fue.

   Las filas NO se borran al quitar el check, y eso es a propósito. Si se
   borraran, cualquier otro aparato que todavía tuviera la casa guardada la
   volvería a subir al abrir la app y el check reaparecería en todos lados.
   Con la fila en falso hay algo que comparar, y gana la fecha más nueva: la
   última vez que alguien tocó el check, sea para ponerlo o para quitarlo. */
create table if not exists public.terminadas (
  casa_norm text primary key,
  cerrada   boolean not null default true,
  fecha     timestamptz not null
);

/* Para los proyectos que crearon la tabla antes de que existiera la columna.
   Las filas que ya estaban eran todas cierres, así que el default les calza. */
alter table public.terminadas add column if not exists cerrada boolean not null default true;

/* ── Ajustes de la app ────────────────────────────────────────────────────
   Una fila por ajuste, con el valor entero en un jsonb. Hoy el único que se
   guarda son los textos del reporte, los que se cambian desde la tuerca.

   Acá gana el más nuevo, entero: son textos que se escriben de tanto en
   tanto y desde un solo lado, y mezclar la mitad de un aparato con la mitad
   del otro sería peor que elegir uno. */
create table if not exists public.ajustes (
  clave text primary key,
  valor jsonb not null,
  fecha timestamptz not null
);

/* ── Acceso ───────────────────────────────────────────────────────────────
   Hacen falta LAS DOS COSAS, y son distintas:

     · el GRANT dice si el rol puede tocar la tabla;
     · la POLICY dice qué filas puede ver de esa tabla.

   Sin el GRANT, la policy no sirve de nada: PostgREST contesta «permission
   denied for table». Supabase pone el GRANT solo cuando las tablas se crean
   desde su interfaz; creándolas con «create table» acá, hay que ponerlo a mano.

   El rol `anon` es el que usa la app, porque va sin login.

   Las reglas son deliberadamente permisivas: es lo que significa «sin login». */
grant select, insert, update, delete on public.reportes   to anon, authenticated;
grant select, insert, update, delete on public.filas      to anon, authenticated;
grant select, insert, update, delete on public.marcas     to anon, authenticated;
grant select, insert, update, delete on public.codigos    to anon, authenticated;
grant select, insert, update, delete on public.terminadas to anon, authenticated;
grant select, insert, update, delete on public.ajustes    to anon, authenticated;

/* RLS queda encendido igual: sin encenderlo, PostgREST no expone las tablas. */
alter table public.reportes   enable row level security;
alter table public.filas      enable row level security;
alter table public.marcas     enable row level security;
alter table public.codigos    enable row level security;
alter table public.terminadas enable row level security;
alter table public.ajustes    enable row level security;

/* El «drop policy if exists» antes de cada una es lo que permite correr este
   archivo de nuevo sin que reviente por nombre repetido. */
drop policy if exists "abierto" on public.reportes;
create policy "abierto" on public.reportes for all to anon, authenticated
  using (true) with check (true);

drop policy if exists "abierto" on public.filas;
create policy "abierto" on public.filas for all to anon, authenticated
  using (true) with check (true);

drop policy if exists "abierto" on public.marcas;
create policy "abierto" on public.marcas for all to anon, authenticated
  using (true) with check (true);

drop policy if exists "abierto" on public.codigos;
create policy "abierto" on public.codigos for all to anon, authenticated
  using (true) with check (true);

drop policy if exists "abierto" on public.terminadas;
create policy "abierto" on public.terminadas for all to anon, authenticated
  using (true) with check (true);

drop policy if exists "abierto" on public.ajustes;
create policy "abierto" on public.ajustes for all to anon, authenticated
  using (true) with check (true);
