/* ══════════════════════════════════════════════════════════════════════════
   Reportes — las tablas en Supabase

   Se corre UNA SOLA VEZ, desde el panel de Supabase:
     SQL Editor → New query → pegar todo esto → Run

   ⚠️ LEER ESTO, QUE NO ES UN DETALLE

   Esta base va SIN login, por decisión tomada a propósito. Eso quiere decir que
   las tablas de acá quedan abiertas a quien tenga la clave pública de la app, y
   esa clave está dentro de `js/nube.js`, en un repositorio público. Cualquiera
   que la encuentre puede leer, cambiar y borrar todo lo que haya acá.

   Se aceptó ese riesgo porque:
     · los datos son avance de obra, no datos personales ni contraseñas;
     · cada aparato conserva su copia completa en IndexedDB, así que vaciar la
       nube no borra el trabajo de nadie;
     · los .xlsx semanales siguen siendo el respaldo de verdad.

   Si algún día se quiere cerrar: se agrega una columna `user_id uuid default
   auth.uid()` a las tres tablas, se cambian las reglas de `to anon` a
   `to authenticated` con `user_id = auth.uid()`, y se le vuelve a poner el
   formulario de entrar a la app.
   ══════════════════════════════════════════════════════════════════════════ */

/* ── Reportes importados ───────────────────────────────────────────────────
   La llave es un uid que genera el aparato al importar el Excel, y no un
   número que ponga la base. Así el mismo reporte tiene la misma identidad en
   la compu, en el celular y en la nube, y sincronizar se vuelve repetible:
   subir dos veces el mismo reporte no lo duplica. */
create table public.reportes (
  uid         uuid primary key,
  nombre      text not null,
  fecha       timestamptz not null,
  hoja        text,
  total_filas integer,
  mapeo       jsonb,
  creado      timestamptz not null default now()
);

/* ── Las casas de cada reporte ────────────────────────────────────────────
   Al borrar un reporte se van sus filas solas (on delete cascade). */
create table public.filas (
  id              bigint generated by default as identity primary key,
  reporte_uid     uuid not null references public.reportes (uid) on delete cascade,
  casa            text not null,
  casa_norm       text not null,
  porcentaje      integer,
  etapa           integer,
  complementarias integer,
  datos           jsonb
);

create index filas_por_reporte on public.filas (reporte_uid);
create index filas_por_casa    on public.filas (casa_norm);

/* ── Las marcas de «añadido» ──────────────────────────────────────────────
   Van por número de casa y no por reporte, igual que en la app: son lo único
   que no se puede regenerar del Excel, así que son lo más importante de
   sincronizar. Con casa_norm como llave, volver a subir la misma marca la
   actualiza en vez de duplicarla. */
create table public.marcas (
  casa_norm text primary key,
  fecha     timestamptz not null
);

/* ── Acceso ───────────────────────────────────────────────────────────────
   Hacen falta LAS DOS COSAS, y son distintas:

     · el GRANT dice si el rol puede tocar la tabla;
     · la POLICY dice qué filas puede ver de esa tabla.

   Sin el GRANT, la policy no sirve de nada: PostgREST contesta «permission
   denied for table». Supabase pone el GRANT solo cuando las tablas se crean
   desde su interfaz; creándolas con «create table» acá, hay que ponerlo a mano.

   El rol `anon` es el que usa la app, porque va sin login.

   Las reglas son deliberadamente permisivas: es lo que significa «sin login». */
grant select, insert, update, delete on public.reportes to anon, authenticated;
grant select, insert, update, delete on public.filas    to anon, authenticated;
grant select, insert, update, delete on public.marcas   to anon, authenticated;

/* RLS queda encendido igual: sin encenderlo, PostgREST no expone las tablas. */
alter table public.reportes enable row level security;
alter table public.filas    enable row level security;
alter table public.marcas   enable row level security;

create policy "abierto" on public.reportes for all to anon, authenticated
  using (true) with check (true);

create policy "abierto" on public.filas for all to anon, authenticated
  using (true) with check (true);

create policy "abierto" on public.marcas for all to anon, authenticated
  using (true) with check (true);
